/**
 * WITDOM Broker API
 * API to use services from the Broker
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package eu.witdom.core.broker.client.api;

import eu.witdom.core.broker.client.ApiClient;
import eu.witdom.core.broker.client.ApiException;
import eu.witdom.core.broker.client.model.Error;
import eu.witdom.core.broker.client.model.ForwardCallback;
import eu.witdom.core.broker.client.model.ForwardRequest;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.util.Objects;

/**
 * API tests for ForwardApi
 */
public class ForwardApiTest {

    String basePath = "http://localhost:5000/v1";
    private ApiClient client = new ApiClient().setBasePath(basePath);
    private final ForwardApi api = new ForwardApi(client);

    
    /**
     * Forward request response to a WITDOM domain
     *
     * This request allows the broker to forward one response to the  broker in the trusted domain, where the target application is located.  This path can only be accessed from a trusted component, so a valid client  certificate must be present on the request. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void forwardCallbackPOSTTest() throws ApiException {
        ForwardCallback forwardCallback = new ForwardCallback();

        forwardCallback.setRequestId("string");
        forwardCallback.setResponseStatus(0);
        
        ObjectMapper mapper = new ObjectMapper();
        ObjectNode objectNode = mapper.createObjectNode();
        objectNode.put("X-header", "header value");

        forwardCallback.setResponseHeaders(objectNode);

        objectNode = mapper.createObjectNode();
        objectNode.put("Key", "value");

        forwardCallback.setResponseData(objectNode);

        try {
            api.forwardCallbackPOST(forwardCallback);
        } catch(Exception ex) {
            
        }

        // TODO: test validations
    }

    /**
     * Forward request to a WITDOM domain
     *
     * This request allows the broker to forward one request to the broker in the untrusted domain, where the target service is located. This path can only be accessed from a trusted component, so a valid client certificate must be present on the request.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void forwardDomainPOSTTest() throws ApiException {

        ForwardRequest forwardRequest = new ForwardRequest();

        forwardRequest.setRequestId("string");
        forwardRequest.setServiceName("string");
        forwardRequest.setRequestType("string");
        forwardRequest.setRequestUri("string");

        ObjectMapper mapper = new ObjectMapper();
        ObjectNode objectNode = mapper.createObjectNode();
        objectNode.put("X-header", "header value");

        forwardRequest.setRequestHeaders(objectNode);

        objectNode = mapper.createObjectNode();
        objectNode.put("Key", "value");

        forwardRequest.setRequestData(objectNode);

        String response = api.forwardDomainPOST(forwardRequest);

        // TODO: test validations
    }
    
}
