version: '2'

services:
  mongo:
    container_name: mongo-broker-td
    image: mongo
    ports:
      - 27017:27017

  mongo2:
    container_name: mongo-broker-ud
    image: mongo
    expose:
      - "27017"

  iam:
    container_name: iam
    build:
      context: dependencies/iam/keystone/docker
    ports:
      - 5001:5000
      - 35357:35357

  broker-td:
    container_name: broker_trusted
    build: .
    image: witdom-core-broker
    ports:
      - 5000:5000
      - 5043:5043
    depends_on:
      - mongo
      - iam
    env_file:
      - td.env

  broker-ud:
    container_name: broker_untrusted
    image: witdom-core-broker
    ports:
      - 5100:5000
      - 5143:5043
    depends_on:
      - broker-td
      - mongo2
    env_file:
      - ud.env