/**
 * WITDOM Broker API
 * API to use services from the Broker
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package eu.witdom.core.broker.client.api;

import eu.witdom.core.broker.client.ApiException;
import eu.witdom.core.broker.client.model.Service;
import eu.witdom.core.broker.client.model.Error;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServicesApi
 */
public class ServicesApiTest {

    private final ServicesApi api = new ServicesApi();

    
    /**
     * Details like location of a specific services
     *
     * This request will throw as result the details of a service.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceDetailsGETTest() throws ApiException {
        String service = null;
        // Service response = api.serviceDetailsGET(service);

        // TODO: test validations
    }
    
    /**
     * List of services available in the domain
     *
     * This request throws as a result the list of all the services and modules associated with the deployment manager of the trusted domain.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceDomainlistGETTest() throws ApiException {
        // List<Service> response = api.serviceDomainlistGET();

        // TODO: test validations
    }
    
    /**
     * List of services available in WITDOM
     *
     * This request will throw as result a list of all the services and modules deployed in WITDOM
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceListGETTest() throws ApiException {
        // List<Service> response = api.serviceListGET();

        // TODO: test validations
    }
    
    /**
     * Time Estimates
     *
     * This request throws as a result the list of all the services and modules associated with the deployment manager outside the trusted domain.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceOutsidelistGETTest() throws ApiException {
        // List<Service> response = api.serviceOutsidelistGET();

        // TODO: test validations
    }
    
}
